name: Run test script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your Python version

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the test script
      - name: Run test.py
        run: python tests/test.py

      # Verify the existence of a .txt file and a .tsv file in the logs/ folder
      - name: Verify logs folder contains the required files
        run: |
          if [ -d "logs" ]; then
            txt_count=$(find logs/ -type f -name "*.txt" | wc -l)
            tsv_count=$(find logs/ -type f -name "*.tsv" | wc -l)

            if [ "$txt_count" -eq 0 ]; then
              echo "Test failed: No .txt file found in logs/"
              exit 1
            fi

            if [ "$tsv_count" -eq 0 ]; then
              echo "Test failed: No .tsv file found in logs/"
              exit 1
            fi

            echo "Test passed: Required files found in logs/"
          else
            echo "Test failed: logs/ folder does not exist."
            exit 1
          fi
